apiVersion: v1
kind: Service
metadata:
  name: service-user
  labels:
    service: backend-user
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    service: backend-user
